apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "open-meta-data"
  region: "ap-northeast-1"
  version: "1.32"

vpc:
  id: "VPC_ID"
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
  subnets:
    public:
      ap-northeast-1a:
        id: "SUBNET_ID_1A"
      ap-northeast-1c:
        id: "SUBNET_ID_1C"
      ap-northeast-1d:
        id: "SUBNET_ID_1D"

nodeGroups:
  - name: "node-group"
    instanceType: m5.xlarge
    minSize: 1
    desiredCapacity: 1
    maxSize: 1
    availabilityZones: ["ap-northeast-1c"]
    privateNetworking: false
    volumeSize: 30
